baseURL = "http://caas-one.github.io/"
languageCode = "en-us"
title = "CaaSOne"
theme = "maupassant"
hasCJKLanguage = true
[params]
  busuanzi = true
[taxonomies]
tag = "tags"
category = "categories"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 4
